apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: world-cup-api
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: world-cup-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: world-cup-secrets
    creationPolicy: Owner
  data:
    - secretKey: FOOTBALL_API_KEY
      remoteRef:
        key: {{ .Values.secrets.footballApi }}
        property: FOOTBALL_API_KEY
    - secretKey: FOOTBALL_API_URL
      remoteRef:
        key: {{ .Values.secrets.footballApi }}
        property: FOOTBALL_API_URL
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.dbSecretArn }}
        property: password
    - secretKey: DB_USERNAME
      remoteRef:
        key: {{ .Values.secrets.dbSecretArn }}
        property: username
